version: "3.7"

services:
  influxdb:
    image: influxdb:1.8.10
    ports:
      - "8086:8086"
    networks:
      - osrs-network
    environment:
      - INFLUXDB_HTTP_ENABLED=true
    volumes:
      - influxdb:/var/lib/influxdb
  osrs-metrics:
    build: .
    ports:
      - "5000:5000"
    environment:
      - HOST=influxdb
      - DB_NAME=osrs_hs_metrics
    links:
      - influxdb
    networks:
      - osrs-network
    volumes:
      - osrs-metrics:/usr/src/osrs
networks:
  osrs-network:
volumes:
  influxdb:
  osrs-metrics: